include(InstallRequiredSystemLibraries)

set(CPACK_SOURCE_GENERATOR "ZIP;TGZ;TZ:")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

set(CPACK_PACKAGE_VERSION_MAJOR "${CMAKE_PROJECT_VERSION_MAJOR}") 
set(CPACK_PACKAGE_VERSION_MINOR "${CMAKE_PROJECT_VERSION_MINOR}") 
set(CPACK_PACKAGE_VERSION_PATCH "${CMAKE_PROJECT_VERSION_PATCH}") 
set(CPACK_PACKAGE_VERSION_TWEAK "${CMAKE_PROJECT_VERSION_TWEAK}")
set(CPACK_PACKAGE_VERSION "${CMAKE_PROJECT_VERSION}")

include(CPack)
